print("Available Commands:")
print("  i<text> : Insert <text> at cursor")
print("  a<text> : Append <text> after cursor")
print("  h       : Move cursor left")
print("  l       : Move cursor right")
print("  k       : Move cursor up")  # Note: Swapped j/k to match vim convention
print("  j       : Move cursor down")  # Note: Swapped j/k to match vim convention
print("  b       : Move cursor to beginning of previous word")
print("  w       : Move cursor to beginning of next word")
print("  ^       : Move cursor to beginning of the line")
print("  $       : Move cursor to end of the line")
print("  x       : Delete character under cursor")
print("  dw      : Delete word starting at cursor")
print("  dd      : Delete current line")
print("  yy      : Yank (copy) current line")
print("  p       : Put (paste) yanked line below current line")
print("  P       : Put (paste) yanked line above current line")
print("  o       : Open (insert) blank line below and move cursor to it")
print("  O       : Open (insert) blank line above and move cursor to it")
print("  u       : Undo last change")
print("  r       : Redo/Repeat last command (if supported)")  # Clarified 'r'
print("  ;       : Toggle row cursor visibility (*)")
print("  .       : Toggle column cursor visibility (highlight)")
print("  ?       : Show this help message")
print("  q       : Quit the editor")